#!/bin/sh

mkdir -p /data/logs
DATETIME=`date +%Y-%m-%d:%H:%M:%S`
DATE=`date +%Y-%m-%d`

echo $DATETIME >> /data/logs/hourly.${DATE}.log


echo "###################"$DATE"#check stock job #################" >> /data/logs/hourly.${DATE}.log
# 增加发送stock 系统地址邮件
/usr/local/bin/python3 /data/stock/jobs/check_job.py >> /data/logs/hourly.${DATE}.log

# 清除20天前日志数据。
DATE_20=`date -d '-20 days' +%Y-%m-%d`
echo "rm -f /data/logs/hourly.${DATE_20}.log"
rm -f /data/logs/hourly.${DATE_20}.log